//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Sport_Products.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderProductId { get; set; }
        public Nullable<int> OrderProductQuantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public static implicit operator OrderProduct(HashSet<OrderProduct> v)
        {
            throw new NotImplementedException();
        }
    }
}
