//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Sport_Products.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> ProductCost { get; set; }
        public Nullable<int> ProductDiscount { get; set; }
        public Nullable<int> ProductManufactureId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual Manufacture Manufacture { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
        public int ProductCostWithDiscount { get; internal set; }
    }
}
